# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from transmission.pallier import data_pb2 as transmission_dot_data__pb2


class safeTransmissionStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.exchangeData = channel.unary_unary(
                '/safeTransmission/exchangeData',
                request_serializer=transmission_dot_data__pb2.secret.SerializeToString,
                response_deserializer=transmission_dot_data__pb2.globalDist.FromString,
                )


class safeTransmissionServicer(object):
    """Missing associated documentation comment in .proto file."""

    def exchangeData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_safeTransmissionServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'exchangeData': grpc.unary_unary_rpc_method_handler(
                    servicer.exchangeData,
                    request_deserializer=transmission_dot_data__pb2.secret.FromString,
                    response_serializer=transmission_dot_data__pb2.globalDist.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'safeTransmission', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class safeTransmission(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def exchangeData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/safeTransmission/exchangeData',
            transmission_dot_data__pb2.secret.SerializeToString,
            transmission_dot_data__pb2.globalDist.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
