# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from transmission.tenseal_mi import tenseal_mi_sche_server_pb2 as transmission_dot_tenseal__mi_dot_tenseal__mi__sche__server__pb2


class MIScheServerServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.decrypt_sort = channel.unary_unary(
                '/MIScheServerService/decrypt_sort',
                request_serializer=transmission_dot_tenseal__mi_dot_tenseal__mi__sche__server__pb2.mi_sche_msg.SerializeToString,
                response_deserializer=transmission_dot_tenseal__mi_dot_tenseal__mi__sche__server__pb2.mi_sche_top_k.FromString,
                )


class MIScheServerServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def decrypt_sort(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MIScheServerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'decrypt_sort': grpc.unary_unary_rpc_method_handler(
                    servicer.decrypt_sort,
                    request_deserializer=transmission_dot_tenseal__mi_dot_tenseal__mi__sche__server__pb2.mi_sche_msg.FromString,
                    response_serializer=transmission_dot_tenseal__mi_dot_tenseal__mi__sche__server__pb2.mi_sche_top_k.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'MIScheServerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class MIScheServerService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def decrypt_sort(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/MIScheServerService/decrypt_sort',
            transmission_dot_tenseal__mi_dot_tenseal__mi__sche__server__pb2.mi_sche_msg.SerializeToString,
            transmission_dot_tenseal__mi_dot_tenseal__mi__sche__server__pb2.mi_sche_top_k.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
