# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from transmission.tenseal import tenseal_key_server_pb2 as transmission_dot_tenseal_dot_tenseal__key__server__pb2


class KeyServerServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.find_top_k = channel.unary_unary(
                '/KeyServerService/find_top_k',
                request_serializer=transmission_dot_tenseal_dot_tenseal__key__server__pb2.key_server_msg.SerializeToString,
                response_deserializer=transmission_dot_tenseal_dot_tenseal__key__server__pb2.top_k_key_server.FromString,
                )


class KeyServerServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def find_top_k(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_KeyServerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'find_top_k': grpc.unary_unary_rpc_method_handler(
                    servicer.find_top_k,
                    request_deserializer=transmission_dot_tenseal_dot_tenseal__key__server__pb2.key_server_msg.FromString,
                    response_serializer=transmission_dot_tenseal_dot_tenseal__key__server__pb2.top_k_key_server.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'KeyServerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class KeyServerService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def find_top_k(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/KeyServerService/find_top_k',
            transmission_dot_tenseal_dot_tenseal__key__server__pb2.key_server_msg.SerializeToString,
            transmission_dot_tenseal_dot_tenseal__key__server__pb2.top_k_key_server.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
