# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transmission/tenseal/tenseal_key_server.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='transmission/tenseal/tenseal_key_server.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n-transmission/tenseal/tenseal_key_server.proto\";\n\x0ekey_server_msg\x12\x11\n\tgroup_key\x18\x01 \x01(\t\x12\t\n\x01k\x18\x02 \x01(\x05\x12\x0b\n\x03msg\x18\x03 \x01(\x0c\"6\n\x10top_k_key_server\x12\x11\n\tgroup_key\x18\x01 \x01(\t\x12\x0f\n\x07ranking\x18\x02 \x03(\x05\x32\x44\n\x10KeyServerService\x12\x30\n\nfind_top_k\x12\x0f.key_server_msg\x1a\x11.top_k_key_serverb\x06proto3'
)




_KEY_SERVER_MSG = _descriptor.Descriptor(
  name='key_server_msg',
  full_name='key_server_msg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='group_key', full_name='key_server_msg.group_key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='k', full_name='key_server_msg.k', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='msg', full_name='key_server_msg.msg', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=49,
  serialized_end=108,
)


_TOP_K_KEY_SERVER = _descriptor.Descriptor(
  name='top_k_key_server',
  full_name='top_k_key_server',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='group_key', full_name='top_k_key_server.group_key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ranking', full_name='top_k_key_server.ranking', index=1,
      number=2, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=110,
  serialized_end=164,
)

DESCRIPTOR.message_types_by_name['key_server_msg'] = _KEY_SERVER_MSG
DESCRIPTOR.message_types_by_name['top_k_key_server'] = _TOP_K_KEY_SERVER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

key_server_msg = _reflection.GeneratedProtocolMessageType('key_server_msg', (_message.Message,), {
  'DESCRIPTOR' : _KEY_SERVER_MSG,
  '__module__' : 'transmission.tenseal.tenseal_key_server_pb2'
  # @@protoc_insertion_point(class_scope:key_server_msg)
  })
_sym_db.RegisterMessage(key_server_msg)

top_k_key_server = _reflection.GeneratedProtocolMessageType('top_k_key_server', (_message.Message,), {
  'DESCRIPTOR' : _TOP_K_KEY_SERVER,
  '__module__' : 'transmission.tenseal.tenseal_key_server_pb2'
  # @@protoc_insertion_point(class_scope:top_k_key_server)
  })
_sym_db.RegisterMessage(top_k_key_server)



_KEYSERVERSERVICE = _descriptor.ServiceDescriptor(
  name='KeyServerService',
  full_name='KeyServerService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=166,
  serialized_end=234,
  methods=[
  _descriptor.MethodDescriptor(
    name='find_top_k',
    full_name='KeyServerService.find_top_k',
    index=0,
    containing_service=None,
    input_type=_KEY_SERVER_MSG,
    output_type=_TOP_K_KEY_SERVER,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_KEYSERVERSERVICE)

DESCRIPTOR.services_by_name['KeyServerService'] = _KEYSERVERSERVICE

# @@protoc_insertion_point(module_scope)
