# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transmission/tenseal_data.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='transmission/tenseal_data.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1ftransmission/tenseal_data.proto\"-\n\tencrypted\x12\x13\n\x0b\x63lient_rank\x18\x01 \x01(\x05\x12\x0b\n\x03msg\x18\x02 \x01(\x0c\x32;\n\x10SafeTransmission\x12\'\n\rsum_encrypted\x12\n.encrypted\x1a\n.encryptedb\x06proto3'
)




_ENCRYPTED = _descriptor.Descriptor(
  name='encrypted',
  full_name='encrypted',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='client_rank', full_name='encrypted.client_rank', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='msg', full_name='encrypted.msg', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=35,
  serialized_end=80,
)

DESCRIPTOR.message_types_by_name['encrypted'] = _ENCRYPTED
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

encrypted = _reflection.GeneratedProtocolMessageType('encrypted', (_message.Message,), {
  'DESCRIPTOR' : _ENCRYPTED,
  '__module__' : 'transmission.tenseal_data_pb2'
  # @@protoc_insertion_point(class_scope:encrypted)
  })
_sym_db.RegisterMessage(encrypted)



_SAFETRANSMISSION = _descriptor.ServiceDescriptor(
  name='SafeTransmission',
  full_name='SafeTransmission',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=82,
  serialized_end=141,
  methods=[
  _descriptor.MethodDescriptor(
    name='sum_encrypted',
    full_name='SafeTransmission.sum_encrypted',
    index=0,
    containing_service=None,
    input_type=_ENCRYPTED,
    output_type=_ENCRYPTED,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SAFETRANSMISSION)

DESCRIPTOR.services_by_name['SafeTransmission'] = _SAFETRANSMISSION

# @@protoc_insertion_point(module_scope)
